/drone/src/src/Hive.Api/Controllers/NewController.cs(37,13): error CA1861: Prefer 'static readonly' fields over constant array arguments if the called method is called repeatedly and is not mutating the passed array (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1861) [/drone/src/src/Hive.Api/Hive.Api.csproj]